#!/usr/bin/env python3
"""
MD File Organizer for SixtySeven AI Workspace

This script analyzes and organizes the numerous MD files generated by the LLM
into a structured folder hierarchy for better management.

Usage:
    python md_organizer.py [--dry-run] [--verbose]

Options:
    --dry-run: Preview changes without actually moving files
    --verbose: Show detailed output
"""

import os
import shutil
import argparse
import re
from pathlib import Path
from typing import Dict, List, Tuple

class MDOrganizer:
    def __init__(self, root_dir: str, dry_run: bool = False, verbose: bool = False):
        self.root_dir = Path(root_dir)
        self.dry_run = dry_run
        self.verbose = verbose
        self.docs_dir = self.root_dir / "docs"

        # Define categorization rules
        self.categories = {
            'promptforge': {
                'pattern': re.compile(r'^PROMPTFORGE_'),
                'folder': 'promptforge'
            },
            'game_themes': {
                'pattern': re.compile(r'^GAME_THEME_'),
                'folder': 'game-themes'
            },
            'mobile': {
                'pattern': re.compile(r'^MOBILE_|^README_MOBILE_'),
                'folder': 'mobile'
            },
            'deployment': {
                'pattern': re.compile(r'^DEPLOYMENT_'),
                'folder': 'deployment'
            },
            'themes': {
                'pattern': re.compile(r'^THEME_|^INDEX_SECTION_|^GAME_THEME_'),
                'folder': 'themes'
            },
            'powerup': {
                'pattern': re.compile(r'^POWERUP_'),
                'folder': 'powerup'
            },
            'fixes': {
                'pattern': re.compile(r'^FIXES_|^DELIVERY_|^L1_IMPLEMENTATION_'),
                'folder': 'fixes'
            },
            'brand': {
                'pattern': re.compile(r'^AGENT\.md$'),
                'folder': 'brand'
            },
            'general': {
                'pattern': re.compile(r'.*'),  # Catch-all for remaining files
                'folder': 'general'
            }
        }

    def find_md_files(self) -> List[Path]:
        """Find all MD files in the root directory (not in subfolders)"""
        return list(self.root_dir.glob("*.md"))

    def categorize_file(self, file_path: Path) -> str:
        """Determine the category for a given file"""
        filename = file_path.name

        for category, rules in self.categories.items():
            if rules['pattern'].match(filename):
                return rules['folder']

        # Default category for uncategorized files
        return 'general'

    def create_folders(self):
        """Create the necessary folder structure"""
        if self.dry_run:
            print(f"DRY RUN: Would create directory {self.docs_dir}")
            for category in self.categories.values():
                folder_path = self.docs_dir / category['folder']
                print(f"DRY RUN: Would create directory {folder_path}")
        else:
            self.docs_dir.mkdir(exist_ok=True)
            for category in self.categories.values():
                folder_path = self.docs_dir / category['folder']
                folder_path.mkdir(exist_ok=True)
                if self.verbose:
                    print(f"Created directory: {folder_path}")

    def move_file(self, source: Path, destination: Path) -> bool:
        """Move a file from source to destination"""
        try:
            if self.dry_run:
                print(f"DRY RUN: Would move {source} -> {destination}")
                return True
            else:
                # Preserve modification time
                stat = source.stat()
                shutil.move(str(source), str(destination))
                os.utime(destination, (stat.st_atime, stat.st_mtime))
                if self.verbose:
                    print(f"Moved: {source} -> {destination}")
                return True
        except Exception as e:
            print(f"Error moving {source} to {destination}: {e}")
            return False

    def generate_index(self, moved_files: Dict[str, List[Tuple[Path, Path]]]):
        """Generate an index file showing the new organization"""
        index_path = self.docs_dir / "README.md"

        content = "# Documentation Index\n\n"
        content += "This index shows the organized documentation structure.\n\n"

        for category, files in moved_files.items():
            if files:
                content += f"## {category.title()}\n\n"
                for original, new in files:
                    rel_path = new.relative_to(self.docs_dir)
                    content += f"- [{original.name}]({rel_path})\n"
                content += "\n"

        if self.dry_run:
            print(f"DRY RUN: Would create index at {index_path}")
            print("Index content preview:")
            print(content[:500] + "..." if len(content) > 500 else content)
        else:
            with open(index_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Created index: {index_path}")

    def organize(self):
        """Main organization method"""
        print("Starting MD file organization...")
        print(f"Root directory: {self.root_dir}")
        print(f"Dry run: {self.dry_run}")
        print(f"Verbose: {self.verbose}")
        print()

        # Find all MD files
        md_files = self.find_md_files()
        print(f"Found {len(md_files)} MD files to process")

        if not md_files:
            print("No MD files found. Exiting.")
            return

        # Create folder structure
        self.create_folders()

        # Categorize and move files
        moved_files = {}
        for file_path in md_files:
            category = self.categorize_file(file_path)
            if category not in moved_files:
                moved_files[category] = []

            destination = self.docs_dir / category / file_path.name
            if self.move_file(file_path, destination):
                moved_files[category].append((file_path, destination))

        # Generate index
        self.generate_index(moved_files)

        # Summary
        total_moved = sum(len(files) for files in moved_files.values())
        print(f"\nOrganization complete! Moved {total_moved} files into {len(moved_files)} categories.")

        if self.dry_run:
            print("This was a dry run. No files were actually moved.")
        else:
            print(f"Check {self.docs_dir} for the organized files.")

def main():
    parser = argparse.ArgumentParser(description="Organize MD files in SixtySeven AI workspace")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without moving files")
    parser.add_argument("--verbose", "-v", action="store_true", help="Show detailed output")
    parser.add_argument("--root", default=".", help="Root directory to process (default: current)")

    args = parser.parse_args()

    # Get the absolute path of the script's directory
    script_dir = Path(__file__).parent.absolute()
    root_dir = (script_dir / args.root).resolve()

    organizer = MDOrganizer(root_dir, dry_run=args.dry_run, verbose=args.verbose)
    organizer.organize()

if __name__ == "__main__":
    main()